# Generated by Django 6.1.1 on 2026-10-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Rol de sistema protegido'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions_data',
            field=models.JSONField(blank=True, default=list, verbose_name='Permisos y funciones asignadas'),
        ),
    ]
