# Generated by Django 6.1.1 on 2026-10-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_seed_system_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación lógica')),
                ('module_id', models.CharField(max_length=50, verbose_name='Módulo')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Descripción')),
                ('is_system', models.BooleanField(default=False, verbose_name='Permiso base del sistema')),
            ],
            options={
                'db_table': 'permiso_definicion',
                'ordering': ['module_id', 'name'],
            },
        ),
    ]
