# Generated by Django 6.1.1 on 2026-09-14 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación lógica')),
                ('affected_table', models.CharField(max_length=50, verbose_name='Tabla afectada')),
                ('affected_record_id', models.CharField(max_length=50, verbose_name='ID de registro afectado')),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Modificación'), ('DELETE', 'Eliminación'), ('VALIDATE', 'Validación'), ('LOGIN', 'Inicio de sesión')], max_length=20, verbose_name='Acción')),
                ('previous_value', models.JSONField(blank=True, null=True, verbose_name='Valor anterior')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='Valor nuevo')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario responsable')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-created_at'],
            },
        ),
    ]
