# Generated by Django 6.1.1 on 2026-09-10 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('activity_code', models.CharField(max_length=50, unique=True)),
                ('activity_date', models.DateField()),
                ('problem_description', models.TextField()),
                ('executed_action', models.TextField()),
                ('contact_name', models.CharField(blank=True, default='', max_length=150)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_collective_agenda', models.BooleanField(default=False)),
                ('validation_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Requires correction', 'Requires correction')], default='Pending', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_code', models.CharField(max_length=50, unique=True)),
                ('file_path', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=150)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='activities.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Requires correction', 'Requires correction')], max_length=30)),
                ('observations', models.TextField(blank=True, default='')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='activities.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
