# Generated by Django 6.1.1 on 2026-09-14 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='evidence',
            options={'verbose_name': 'Evidencia', 'verbose_name_plural': 'Evidencias'},
        ),
        migrations.AlterModelOptions(
            name='validation',
            options={'verbose_name': 'Validación', 'verbose_name_plural': 'Validaciones'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de actividad'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_date',
            field=models.DateField(verbose_name='Fecha de actividad'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre de contacto'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación lógica'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='executed_action',
            field=models.TextField(verbose_name='Acción ejecutada'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_collective_agenda',
            field=models.BooleanField(default=False, verbose_name='¿Ingresa a agenda colectiva?'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='problem_description',
            field=models.TextField(verbose_name='Descripción del problema'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='validation_status',
            field=models.CharField(choices=[('Pending', 'Pendiente'), ('Approved', 'Aprobado'), ('Rejected', 'Rechazado'), ('Requires correction', 'Requiere corrección')], default='Pending', max_length=30, verbose_name='Estado de validación'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='activities.activity', verbose_name='Actividad asociada'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación lógica'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='evidence_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de evidencia'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='file_name',
            field=models.CharField(max_length=150, verbose_name='Nombre del archivo'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='file_path',
            field=models.CharField(max_length=255, verbose_name='Ruta del archivo'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='activities.activity', verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='decision',
            field=models.CharField(choices=[('Approved', 'Aprobado'), ('Rejected', 'Rechazado'), ('Requires correction', 'Requiere corrección')], max_length=30, verbose_name='Decisión'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación lógica'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='observations',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
    ]
