# Generated by Django 6.1.1 on 2026-09-14 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_options_alter_evidence_options_and_more'),
        ('metrics', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación lógica')),
                ('area', models.CharField(max_length=50, verbose_name='Área municipal')),
                ('service', models.CharField(max_length=100, verbose_name='Servicio principal')),
                ('attention_type', models.CharField(max_length=100, verbose_name='Tipo de atención')),
                ('subattention_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Subtipo de atención')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Catálogo de Servicio',
                'verbose_name_plural': 'Catálogo de Servicios',
                'ordering': ['area', 'service'],
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-activity_date', '-created_at'], 'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='evidence',
            options={'ordering': ['-created_at'], 'verbose_name': 'Evidencia', 'verbose_name_plural': 'Evidencias'},
        ),
        migrations.AlterModelOptions(
            name='validation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Validación', 'verbose_name_plural': 'Validaciones'},
        ),
        migrations.AddField(
            model_name='activity',
            name='delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='organization.delegation', verbose_name='Delegación'),
        ),
        migrations.AddField(
            model_name='activity',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='metrics.measurementitem', verbose_name='Ítem de medición asociado'),
        ),
        migrations.AddField(
            model_name='activity',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='metrics.measurementperiod', verbose_name='Período de medición'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario responsable'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidences', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AddField(
            model_name='validation',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_validations', to=settings.AUTH_USER_MODEL, verbose_name='Verificador responsable'),
        ),
        migrations.AddField(
            model_name='activity',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='activities.servicecatalog', verbose_name='Clasificación en catálogo'),
        ),
    ]
