# Generated by Django 6.1.1 on 2026-10-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_servicecatalog_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vecino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación lógica')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('rut', models.CharField(max_length=15, unique=True, verbose_name='RUT')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('territorio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Territorio')),
                ('estado', models.CharField(default='Activo', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Vecino',
                'verbose_name_plural': 'Vecinos',
                'ordering': ['nombre'],
            },
        ),
    ]
