# Generated by Django 6.1.1 on 2026-09-14 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0002_alter_activity_options_alter_evidence_options_and_more'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectiveAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación lógica')),
                ('request_source', models.CharField(choices=[('Interno', 'Solicitud interna municipal'), ('Externo', 'Requerimiento vecinal / ciudadano')], default='Externo', max_length=20, verbose_name='Origen de la solicitud')),
                ('requester', models.CharField(max_length=150, verbose_name='Solicitante / Organización')),
                ('territory', models.CharField(max_length=100, verbose_name='Territorio / Sector')),
                ('support_area', models.CharField(blank=True, default='', max_length=100, verbose_name='Área municipal de apoyo')),
                ('description', models.TextField(verbose_name='Descripción del compromiso')),
                ('committed_date', models.DateField(verbose_name='Fecha comprometida')),
                ('status', models.CharField(choices=[('Ingresado', 'Ingresado'), ('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Realizado', 'Realizado')], default='Ingresado', max_length=30, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observaciones de seguimiento')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_commitments', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario responsable')),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='organization.delegation', verbose_name='Delegación')),
                ('source_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='activities.activity', verbose_name='Actividad de origen')),
            ],
            options={
                'verbose_name': 'Compromiso de Agenda Colectiva',
                'verbose_name_plural': 'Agenda Colectiva (Tubo de Trabajo)',
                'ordering': ['committed_date'],
            },
        ),
        migrations.CreateModel(
            name='CommitmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación lógica')),
                ('previous_status', models.CharField(max_length=30, verbose_name='Estado anterior')),
                ('new_status', models.CharField(max_length=30, verbose_name='Nuevo estado')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observaciones del cambio')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitment_updates', to=settings.AUTH_USER_MODEL, verbose_name='Autor del cambio')),
                ('commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='agenda.collectiveagenda', verbose_name='Compromiso')),
            ],
            options={
                'verbose_name': 'Historial de Compromiso',
                'verbose_name_plural': 'Historial de Compromisos',
                'ordering': ['-created_at'],
            },
        ),
    ]
