# Generated by Django 6.1.1 on 2026-09-14 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación lógica')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nombre del ítem de medición')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción operativa')),
                ('item_type', models.CharField(choices=[('Cuantitativo', 'Cuantitativo (conteo de atenciones)'), ('Porcentual', 'Porcentual (tasa de resolución)')], default='Cuantitativo', max_length=30, verbose_name='Tipo de ítem')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Ítem de Medición',
                'verbose_name_plural': 'Ítems de Medición',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MeasurementPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación lógica')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del período')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de término')),
                ('computable_days', models.PositiveIntegerField(default=90, verbose_name='Días computables')),
                ('minimum_threshold', models.DecimalField(decimal_places=2, default=80.0, max_digits=5, verbose_name='Umbral mínimo colectivo (%)')),
                ('compliance_cap', models.DecimalField(decimal_places=2, default=150.0, max_digits=5, verbose_name='Tope de cumplimiento (%)')),
                ('status', models.CharField(choices=[('Planificado', 'Planificado'), ('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Período de Medición',
                'verbose_name_plural': 'Períodos de Medición',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación lógica')),
                ('adjustment_type', models.CharField(choices=[('Felicitacion', 'Felicitación ciudadana (+%)'), ('Reclamo', 'Reclamo fundamentado (-%)'), ('Penalizacion', 'Penalización operativa (-%)')], max_length=30, verbose_name='Tipo de ajuste')),
                ('percentage_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor porcentual (%)')),
                ('reason', models.TextField(verbose_name='Motivo del ajuste')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_adjustments', to='metrics.measurementperiod', verbose_name='Período')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario')),
            ],
            options={
                'verbose_name': 'Ajuste de Desempeño',
                'verbose_name_plural': 'Ajustes de Desempeño',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación lógica')),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor objetivo / Meta')),
                ('unit_of_measure', models.CharField(default='Atenciones', max_length=30, verbose_name='Unidad de medida')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ponderación (%)')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='organization.position', verbose_name='Cargo evaluado')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='metrics.measurementitem', verbose_name='Ítem medible')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='metrics.measurementperiod', verbose_name='Período de medición')),
            ],
            options={
                'verbose_name': 'Meta de Gestión',
                'verbose_name_plural': 'Metas de Gestión',
                'ordering': ['period', 'position', 'item'],
                'unique_together': {('period', 'position', 'item')},
            },
        ),
        migrations.CreateModel(
            name='DailyIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación lógica')),
                ('calculation_date', models.DateField(verbose_name='Fecha de cálculo')),
                ('accumulated_progress', models.PositiveIntegerField(default=0, verbose_name='Avance acumulado válido')),
                ('compliance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='% Cumplimiento')),
                ('weighted_compliance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Cumplimiento ponderado (%)')),
                ('expected_target_to_date', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Meta esperada al día (%)')),
                ('traffic_light', models.CharField(choices=[('Verde', 'Verde (Avance >= Meta esperada al día)'), ('Ámbar', 'Ámbar (Avance entre 60% y 99% de lo esperado)'), ('Rojo', 'Rojo (Avance < 60% de lo esperado)')], default='Ámbar', max_length=20, verbose_name='Semáforo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_indicators', to=settings.AUTH_USER_MODEL, verbose_name='Funcionario')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_indicators', to='metrics.measurementperiod', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Indicador Diario',
                'verbose_name_plural': 'Indicadores Diarios',
                'ordering': ['-calculation_date', 'user'],
                'unique_together': {('user', 'period', 'calculation_date')},
            },
        ),
    ]
