# Generated by Django 6.1.1 on 2026-09-14 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0003_servicecatalog_alter_activity_options_and_more'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación lógica')),
                ('user_rut', models.CharField(max_length=12, verbose_name='RUT de la persona usuaria')),
                ('user_name', models.CharField(max_length=150, verbose_name='Nombre de la persona usuaria')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Teléfono de contacto')),
                ('entry_date', models.DateField(verbose_name='Fecha de ingreso')),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_cases', to='organization.delegation', verbose_name='Delegación')),
            ],
            options={
                'verbose_name': 'Caso Social',
                'verbose_name_plural': 'Casos Sociales',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='SocialManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación lógica')),
                ('stage', models.PositiveSmallIntegerField(verbose_name='Etapa / N° de gestión (1 a 3)')),
                ('management_type', models.CharField(max_length=100, verbose_name='Tipo de gestión realizada')),
                ('management_date', models.DateField(verbose_name='Fecha de la gestión')),
                ('result', models.TextField(verbose_name='Resultado de la atención')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managements', to='social.socialcase', verbose_name='Caso social asociado')),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_managements', to='activities.servicecatalog', verbose_name='Servicio / Prestación entregada')),
            ],
            options={
                'verbose_name': 'Gestión Social',
                'verbose_name_plural': 'Gestiones Sociales',
                'ordering': ['case', 'stage'],
                'unique_together': {('case', 'stage')},
            },
        ),
    ]
